#!/bin/sh -e

export SOURCE_FILES="nanobar_api tests"

set -x

uv run ruff format --check --diff $SOURCE_FILES
uv run mypy $SOURCE_FILES
uv run ruff check $SOURCE_FILES
uv run nanobar-lint-service-boundaries nanobar_api
